-- 코드를 입력하세요
SELECT A.REST_ID REST_ID, A.REST_NAME REST_NAME, A.FOOD_TYPE FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A, REST_REVIEW B
WHERE 1 = 1
    AND A.REST_ID = B.REST_ID
    AND ADDRESS LIKE '서울%'
GROUP BY A.REST_ID, A.REST_NAME, A.FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;
